---
title: "Data Source and Import"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CDC BRFSS Survey 2023

The Behavioral Risk Factor Surveillance System (BRFSS) was a nationwide survey conducted by the Centers for Disease Control and Prevention (CDC) to gather data on health-related risk behaviors, chronic health conditions, and preventive health practices among adults in the United States. The primary purpose of the BRFSS was to inform public health policy, monitor health trends, and support the development of health interventions. It was one of the largest continuously conducted telephone health surveys in the world, providing critical insights into the health status and needs of U.S. residents. 

The BRFSS used Computer-Assisted Telephone Interviewing (CATI) systems to collect data, with respondents selected through a probability sampling method to ensure results are representative of the U.S. adult population. In 2023, 54 states and territories participated, though data from Pennsylvania and Kentucky were excluded due to insufficient collection. Data collection occurred year-round, spanning all 12 months, and interviews were conducted seven days a week, both during the day and in the evening, to maximize response rates. Interviews lasted an average of 17 minutes for the core questionnaire, with additional time required for optional modules and state-specific questions. The survey incorporated both landline and cellular samples, adjusting for demographic factors such as age, gender, race/ethnicity, education, and marital status through a process known as iterative proportional fitting or raking. This methodology ensured that the BRFSS data was nationally representative and reflective of the diverse U.S. population, making it a valuable tool for understanding and addressing public health challenges.

**For the purposes of our project, we are interested in collecting data related to diabetes, along with other general demographic data, in order to make conclusions about the significant relationships between certain lifestyle and health factors and diabetes.**


## Importing the data

The BRFSS data, as well as the codebook are available [here](https://www.cdc.gov/brfss/annual_data/annual_2023.html). There are 433,323 rows of at least partial surveys. 

We started by importing the data from the XPT format into a .csv. We placed it in our .gitignore because the file was too large.

Then, in our repo at `data_import.rmd`, we chose only the necessary variables, which we decided on in our literature review, and saved it at `data/diabetes.csv` in the [repo](https://github.com/mayakrish85/t2d.github.io/tree/main/data).

## *FINISH LITERATURE REVIEW SECTION*
